SET IDENTITY_INSERT [dbo].[MenuItems] ON
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (1, N'Aloo gobi', 150, N'Aloo gobi is a dry cuisine dish made with potatoes, cauliflower and Indian spices. It is yellowish in color, due to the use of turmeric, and occasionally contains kalonji and curry leaves.', N'Dish', N'Main', N'y')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (2, N'Kulcha', 100, N'Kulcha is a type of leavened bread, made from maida (wheat flour).It is usually eaten with chole.', N'Bread', N'Main', N'y')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (3, N'Baati', 80, N'Baati is a hard, unleavened bread cooked in the desert areas of Rajasthan,and in Uttar Pradesh and Madhya Pradesh. It is prized for its long shelf life and high nutritional content.', N'Bread', N'Main', N'y')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (4, N'Bhatura chole', 100, N'Bhatura chole is a combination of chana masala (spicy chick peas) and fried bread called bhatoora (made of maida flour) from India.', N'Dish', N'Main', N'y')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (5, N'Biryani', 120, N'Biryani  is a mixed rice dish with its origins among the people of the Indian subcontinent.It is popular throughout the subcontinent and among the diaspora from the region.', N'Dish', N'Main', N'n')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (6, N'Butter chicken', 200, N'Butter chicken is an Indian dish of chicken in a mildly spiced curry sauce. It is served in India and abroad. The dish has its roots in Punjabi cuisine and was developed by the Moti Mahal restaurant in Delhi, India.', N'Dish', N'Main', N'n')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (7, N'Chaat', 50, N'Papri chaat is traditionally prepared using crisp fried dough wafers known as papri, along with boiled chick peas, boiled potatoes, yogurt and tamarind chutney and topped with chaat masala and sev.', N'Dish', N'Snack', N'y')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (8, N'Chana masala', 100, N'Chana masala is a popular dish in India. It is fairly dry and spicy with a sour citrus note.', N'Dish', N'Main', N'y')
INSERT INTO [dbo].[MenuItems] ([Id], [name], [price], [description], [type], [course], [isveg]) VALUES (9, N'Dal makhani', 120, N'Dal makhani is a popular dish. The primary ingredients in dal makhani are whole black lentil with red kidney beans, butter and cream.', N'Dish', N'Main', N'y')
SET IDENTITY_INSERT [dbo].[MenuItems] OFF
